from django import forms
from django_countries.fields import CountryField

class ApplicationForm(forms.Form):
    last_name = forms.CharField(max_length=33)
    first_name = forms.CharField(max_length=33)
    no_first_name = forms.BooleanField("No First Name")
    middle_name = forms.CharField(max_length=33)
    no_middle_name = forms.BooleanField("No Middle Name")
    gender_male = forms.BooleanField()
    gender_female = forms.BooleanField()
    birth_month = forms.CharField(max_length=2)
    birth_day = forms.CharField(max_length=2)
    birth_year = forms.CharField(max_length=4)
    birth_city = forms.CharField(max_length=33)
    unknown_birth_city = forms.BooleanField()
    birth_country = CountryField()
    eligibility_country_yes = forms.BooleanField()
    eligibility_country_no = forms.BooleanField()
    eligibility_country = CountryField()
    photo = forms.ImageField()
    mailing_address_in_care_of = forms.CharField(max_length=30)
    mailing_address_line_1 = forms.CharField(max_length=30)
    mailing_address_line_2 = forms.CharField(max_length=30)
    mailing_address_city = forms.CharField(max_length=50)
    mailing_address_provence = forms.CharField(max_length=50)
    mailing_address_postal_code = forms.CharField(max_length=25)
    no_postal_code = forms.BooleanField()
    mailing_address_country = CountryField()
    resident_country = CountryField()
    phone = forms.CharField(max_length=50)
    email = forms.EmailField(max_length=50)
    email_confirmation = forms.EmailField(max_length=50)
    primary_school_only = forms.BooleanField()
    high_school_no_degree = forms.BooleanField()
    high_school_degree = forms.BooleanField()
    vocational_school = forms.BooleanField()
    some_university_courses = forms.BooleanField()
    university_degree = forms.BooleanField()
    some_graduate_level_courses = forms.BooleanField()
    master_degree = forms.BooleanField()
    some_doctorate_level_courses = forms.BooleanField()
    doctorate_degree = forms.BooleanField()
    married_not_usa = forms.BooleanField()
    married_is_usa = forms.BooleanField()
    divorced = forms.BooleanField()
    widowed = forms.BooleanField()
    legally_separated = forms.BooleanField()
    spouse_information = forms.BooleanField()
    num_children = forms.CharField(max_length=2)