from django.db import models
from django_countries.fields import CountryField

# Create your models here.

class ApplicationForm(models.Model):
    last_name = models.CharField(max_length=33)
    first_name = models.CharField(max_length=33)
    no_first_name = models.BooleanField("No First Name")
    middle_name = models.CharField(max_length=33)
    no_middle_name = models.BooleanField("No Middle Name")
    gender_male = models.BooleanField()
    gender_female = models.BooleanField()
    birth_month = models.CharField(max_length=2)
    birth_day = models.CharField(max_length=2)
    birth_year = models.CharField(max_length=4)
    birth_city = models.CharField(max_length=33)
    unknown_birth_city = models.BooleanField()
    birth_country = CountryField()
    eligibility_country_yes = models.BooleanField()
    eligibility_country_no = models.BooleanField()
    eligibility_country = CountryField()
    photo = models.ImageField()
    mailing_address_in_care_of = models.CharField(max_length=30)
    mailing_address_line_1 = models.CharField(max_length=30)
    mailing_address_line_2 = models.CharField(max_length=30)
    mailing_address_city = models.CharField(max_length=50)
    mailing_address_provence = models.CharField(max_length=50)
    mailing_address_postal_code = models.CharField(max_length=25)
    no_postal_code = models.BooleanField()
    mailing_address_country = CountryField()
    resident_country = CountryField()
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    email_confirmation = models.EmailField(max_length=50)
    primary_school_only = models.BooleanField()
    high_school_no_degree = models.BooleanField()
    high_school_degree = models.BooleanField()
    vocational_school = models.BooleanField()
    some_university_courses = models.BooleanField()
    university_degree = models.BooleanField()
    some_graduate_level_courses = models.BooleanField()
    master_degree = models.BooleanField()
    some_doctorate_level_courses = models.BooleanField()
    doctorate_degree = models.BooleanField()
    married_not_usa = models.BooleanField()
    married_is_usa = models.BooleanField()
    divorced = models.BooleanField()
    widowed = models.BooleanField()
    legally_separated = models.BooleanField()
    spouse_information = models.BooleanField()
    num_children = models.CharField(max_length=2)