# Generated by Django 5.1.3 on 2024-12-02 18:54

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=33, verbose_name='Last/Family Name')),
                ('first_name', models.CharField(max_length=33, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=33, null=True, verbose_name='Middle Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('birth_date', models.DateField(blank=True)),
                ('birth_city', models.CharField(max_length=33, verbose_name='Birth City')),
                ('birth_country', django_countries.fields.CountryField(max_length=2)),
                ('eligibility_country', django_countries.fields.CountryField(max_length=2)),
                ('entrant_photograph', models.ImageField(upload_to='')),
                ('mailing_address_in_care_of', models.CharField(blank=True, max_length=33, null=True, verbose_name='In Care Of (optional)')),
                ('mailing_address_address_line_one', models.CharField(max_length=33, verbose_name='Address Line 1')),
                ('mailing_address_address_line_two', models.CharField(blank=True, max_length=33, null=True, verbose_name='Address Line 2 (optional)')),
                ('mailing_adress_city', models.CharField(max_length=50, verbose_name='City/Town')),
                ('mailing_adress_provence', models.CharField(max_length=50, verbose_name='District/County/Province/State')),
                ('mailing_address_zip_code', models.CharField(max_length=33, verbose_name='Postal Code/Zip Code')),
                ('mailing_address_country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('resident_country', django_countries.fields.CountryField(max_length=2)),
                ('phone_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('e_mail', models.EmailField(max_length=254)),
                ('education_level', models.CharField(choices=[('primary school only', 'Primary school only'), ('high school, no degree', 'High School, no degree'), ('high shool degree', 'High School degree'), ('vocational shool', 'Vocational School'), ('some university courses', 'Some University Courses'), ('university degree', 'University Degree'), ('some graduate level courses', 'Some Graduate Level Courses'), ("master's degree", "Master's Degree"), ('some doctorate level courses', 'Some Doctorate Level Courses'), ('doctorate degree', 'Doctorate Degree')], max_length=33)),
                ('marital_status', models.CharField(choices=[('unmarried', 'Unmarried'), ('married_nlpr', 'Married and my spouse is NOT a U.S. citizen or U.S. Lawful Permanent Resident (LPR)'), ('married_lpr', 'Married and my spouse is a U.S. citizen or U.S. Lawful Permanent Resident (LPR)'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('legally separated', 'Legally Separated')], max_length=20)),
                ('number_of_children', models.PositiveSmallIntegerField()),
                ('confirmation_number', models.CharField(blank=True, max_length=16)),
                ('digital_signature', models.CharField(blank=True, max_length=40)),
            ],
        ),
    ]
